### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by swmcc** [belfastruby/belfastruby.github.io#16]
Write some tests to prove that the site still renders properly.

[Matt](https://www.github.com/mattbudde) has already started this but lots more would needed added.

**Comment by Lawrence4code** [comment]
I'd like to help with writing some test cases. Let me know, please.

**Comment by swmcc** [comment]
@Lawrence4code Please go ahead - any help give me a shout :)

**Comment by SarthakAgarwal147** [comment]
Hello everyone, I'm new to open source. So, let me know if you need some help.

**Comment by EshitaNandy** [comment]
I am a beginner to open source projects!
Please let me know in any way I can contribute for your project!

**Comment by swmcc** [comment]
Tests were added. Thank you.
