### ISSUE TITLE
Stop using the redcarpet markdown engine

### ISSUE THREAD

**Issue by swmcc** [belfastruby/belfastruby.github.io#17]
When the site is built an email is sent out stating there is a 'Page build warning'.

It states that  the `redcarpet'``Markdown engine, which we use, is no longer supported by GitHub Pages and can be pulled at anytime.

Simply remove he `engine` from `_config.yml` and make sure the site runs. Or even better make sure the tests run that #16 will introduce.

This a great PR for someone wanting to start to contribute.

**Comment by mattbudde** [comment]
Closing this now that it is merged
