### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by swmcc** [belfastruby/belfastruby.github.io#20]
Now that we have the start of a [test suite](https://github.com/belfastruby/belfastruby.github.io/tree/master/spec) for the [belfastruby](https://www.belfastruby.org) site we should use some form of CI.

I (swm) am not too sure how this would work with GH Pages. However having every branch run the test suite would be a great start.

**Comment by apoclyps** [comment]
Travis CI could be a nice option for this as it's free for open source projects and integrates easily with Github.  I'd be happy to pick up this piece of work but first, the project needs a license attached to it to make use of the generous free open source tier: 

An MIT license seems the most applicable to this project: the Github Community wizard provides an easy way to add a license to the repo: https://github.com/belfastruby/belfastruby.github.io/community

**Comment by swmcc** [comment]
Any update on this? Not putting pressure on it - just wondering.

**Comment by davidjrice** [comment]
Could do this if ya want!

**Comment by swmcc** [comment]
That'd be great 👍

**Comment by davidjrice** [comment]
Can you get the .org access?

**Comment by apoclyps** [comment]
Apologies for holding up this PR; @davidjrice the following PR might give you a helping hand to get started: https://github.com/apoclyps/belfastruby.github.io/pull/1 is successfully building and running tests. The following hasn't been added to the above PR:

* Adding a build badge to the README
* Adding steps to configure the `belfastruby` repository to use travis

**Comment by swmcc** [comment]
You've nothing to apologise for @apoclyps

**Comment by AlanFoster** [comment]
Here's my attempt: https://github.com/belfastruby/belfastruby.github.io/pull/25

Let me know your thoughts :+1:
